const tipps = [
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "vollständige Simulationen ",
    name: "nicooooo (PR 97)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "nein", name: "louis1409 (PR 76)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Personalisiertere Ratschläge und mehr Tipps zum effizienterem Arbeiten",
    name: "Pseudonym (PR 35)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "kurs", name: "louis1409 (PR 76)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Hamnat Vorbereitung ", name: "Gofrahn.Solh (PR 99)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Textverständnis hätte ich öfter mit 4 Texten üben sollen, die Zeiteinteilung hatte ich nicht drin und bin total ins straucheln gekommen. Außerdem sind die MedGurus Texte viel zu lang viel zu leicht.",
    name: "Girlwithblueshirt18! (PR 90)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Lernpartner", name: "Gofrahn.Solh (PR 99)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Immer wieder neue Vorgehensweisen",
    name: "Pseudonym (PR 35)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Nichts", name: "N30L20ZS21 (PR 99)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Simulationen", name: "Pseudonym (PR 35)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Nicht zu viel Zeit in immer die selben Aufgaben investieren ",
    name: "Vivi2106 (PR 98)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Basics üben", name: "Sonnenblume123 (PR 69)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Nachbereitung", name: "Flo18Grün (PR 93)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Nichts, ich konnte ja nicht wissen, dass der Konztest so schwer sein würde. Da hat mir meine Vorbereitung nicht geholfen. ",
    name: "Girlwithblueshirt18! (PR 90)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mit anderen Menschen, die den TMS schreiben, zusammen lernen.",
    name: "Marcella (PR 58)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Frühzeitig anfangen und einen guten Lernplan erstellen",
    name: "Vivi2106 (PR 98)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Die ITB Bücher", name: "N30L20ZS21 (PR 99)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Ein Webinar zu den Ableitbarkeitaufgaben",
    name: "sehrmüde (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Werner und Tobi kennenzulernen ",
    name: "Chelli311001 (PR 90)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Keine ausführliche Nachbereitung der Untertests",
    name: "Lebkuchen (PR 88)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Zeit :-) aber das hat man nie :))",
    name: "fabien38 (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Medgurus Bücher und viele Simulationen, besonders die bei Medbooster mit einer Auswertung. Fast noch wichtiger: Beim Test selbst cool bleiben",
    name: "Girlwithblueshirt18! (PR 90)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu oft in Details verloren",
    name: "Sonnenblume123 (PR 69)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Die Loki Methode besser zu lernen. ",
    name: "Bellatrix (PR 90)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Der Medbooster Kurs", name: "N30L20ZS21 (PR 99)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Die Tests zu lernen, in denen ich mich kaum bis gar nicht verbessert habe.",
    name: "Marcella (PR 58)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: " Mehr Zeit. Vielleicht doch etwas früher anfangen als 1.1.2021",
    name: "Neo.Sami (PR 100)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Simulation", name: "jxsxyxxt (PR 79)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "dauerhaft figuren und fakten", name: "Emily2810 (PR 95)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr simulationen", name: ".x.julia.x. (PR 76)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele Simulationen ( dadurch ist eine feste Routine entstanden)",
    name: "Lebkuchen (PR 88)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Ich habe viel zu viele leichte Aufgabenstellungen von Figuren und Fakten geübt, als dann die schwierigeren kamen, war die Luft raus und das hat sich leider beim TMS bemerkbar gemacht. Also, lieber ein paar leichte Aufgaben überspringen und gleich ins kalte Wasser. ",
    name: "sehrmüde (PR 95)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Üben mit Leuten, die schon geschrieben haben und Tricks kennen und gut weitergeben können ",
    name: "cwhsv21* (PR 88)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mich nicht allzu sehr unter Druck zu setzen.",
    name: "Marcella (PR 58)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "eigentlich nichts - ich habe gebrauchte Bücher für 50 € gekauft, mit denen ich super lernen konnte (es muss nicht immer alles neu sein) - \nZeitlich habe ich parallel meine Bachelorarbeit geschrieben, da habe ich mich manchmal verflucht, dass ich nicht so viel Zeit zum lernen hatte ",
    name: "fabien38 (PR 85)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Fakten mit dopplungen ", name: "s331319! (PR 85)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "einfach dran bleiben ", name: "Emily2810 (PR 95)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: " -", name: "Neo.Sami (PR 100)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "weniger Fehler im Vorbereitungsmaterial",
    name: "Mediklas (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "kontinuierlich lernen; Kreuzblick verwenden; Simulationen durchmachen; Nachbereiten ",
    name: "sehrmüde (PR 95)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Blindes üben", name: "Solafide_1 (PR 95)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Ein breiteres Wissen über die medizinische Themen (für MedNat und TV) haben",
    name: "maria.v.v. (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Nicht nachlassen und immer nachbereiten",
    name: "fabien38 (PR 85)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Genaues zusammenfassen zu Beginn der Untertests und allen Infos aus allen Büchern dazu",
    name: "Mexicana (PR 99)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "nichts, alles gut gewesen so", name: "celinawerner (PR 93)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ich habe mich nicht gestresst.",
    name: "Bellatrix (PR 90)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Einfach drauf loslernen ohne überhaupt eine Strategie zu haben. Ich habe erst nach dem Kurs verstanden worauf es ankommt bei den einzelnen Untertests",
    name: "Bina2225 (PR 79)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Zeit (Abi parallel geschrieben)",
    name: "Annika_1807 (PR 93)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Frühzeitig mit Lernen anfangen und komplett durchziehen. 2 Stunden jeden Tag, auch wenns einen so auf die Nerven ging. Dabei einige komplette Simulation machen.",
    name: "Neo.Sami (PR 100)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Die TMS Studie", name: "25ooo2oo (PR 26)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Andere konzentrationsbücher verwenden ",
    name: "Franziska (PR 95)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Kurs mit strategien", name: "Solafide_1 (PR 95)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Ab und zu, zu viel Stress und Gedanken machen und den Glauben an sich selbst in Frage stellen ",
    name: "cwhsv21* (PR 88)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Geduld und Motivation ", name: "Emma :)  (PR 93)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Endspurt Simulation ", name: "Alissa.p. (PR 88)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Zu wenig Taktik am Anfang", name: "Mediklas (PR 99)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Zeit ", name: "Charly26 (PR 39)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Bücher anschaffen und mit anderen Ideen austauschen",
    name: ".x.julia.x. (PR 76)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Üben ohne Nachbereitung ", name: "maria.v.v. (PR 95)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Hilfe bei MedNat und TestV", name: "Clea2601 (PR 76)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viel üben und viele Simulationen machen",
    name: "Mexicana (PR 99)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Fokus auf TV und MedNat", name: "Medi1234 (PR 73)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Vielleicht am Ende noch etwas mehr Bewegung auf dem Slackserver, es wurde irgendwann so still\nAndererseits wars vielleicht auch das Richtige so😅",
    name: "20Flusensuse30 (PR 99)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Der medbooster kurs", name: "N30L20ZS21 (PR 99)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Ewig nach dem perfekten Konzstift zu suchen",
    name: "Simon123 (PR 100)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Konzentrationstests auf Testniveau (den Schwierigkeitsgrad erfüllte meiner Meinung nach kein Anbieter)",
    name: "IchBinSelbstÜberrascht (PR 93)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mit Lernpartnern arbeiten, komplette Simulationen",
    name: "25ooo2oo (PR 26)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Der Meditrain Kurs ", name: "ali123sch (PR 79)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Motivation, früh anzufangen und das dann auch durchzuziehen",
    name: "mg123456 (PR 69)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Konz lock, simulation und lernpartner ",
    name: "Slaimboo (PR 85)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "konztest üben", name: "c-1h-1i- (PR 79)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Jemanden in meinem Umfeld der den Test auch geschrieben hat und sich auch darauf vorbereitet hat :D dann wäre mir der Austausch um persönlichen Umfeld leichter gefallen",
    name: "GiuliaO112 (PR 88)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Einen Kurs, um uns ganze Geschehen einsteigen zu können, Mitstreiter zu finden und dann mit Büchern fleißig üben und viel reflektieren ",
    name: "cwhsv21* (PR 88)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Das Aufarbeiten von Mathe Grundkenntnissen.",
    name: "Chriso139 (PR 79)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Ging nicht besser, meine Grenzen wurden anscheinend erreicht. Ich hab mein Bestes gegeben",
    name: "Kallahkokku?; (PR 46)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Weiter Konztest und Muster und Diagramme üben es zahlt sich so aus!!!",
    name: "s331319! (PR 85)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "der Vergleich mit anderen, hat mich ab und zu zu unrecht verunsichert",
    name: "celinawerner (PR 93)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Konz-Aufgaben", name: "synedrack1! (PR 92)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Reflektieren und Routine aufbauen",
    name: "Mediklas (PR 99)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Die Stark Simulationen", name: "Annika_1807 (PR 93)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "ruhigere Nerven :D", name: "LarS210* (PR 95)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Genug Zeit für Üben investieren, damit ich am Testtag entspannt sein kann und auch wissen kann, dass ich im Top-Form bin ",
    name: "maria.v.v. (PR 95)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "ITB 1&2 zu kaufen ", name: "12345678 (PR 93)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Lerpartner", name: "Lillifee0511 (PR 97)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Lernpensum", name: "Medi1234 (PR 73)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Sich Stress machen ;)", name: "Franziska (PR 95)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Alles hat gepasst!", name: "0151-L15 (PR 96)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "10 Simulationen insgesamt ",
    name: "Simon123 (PR 100)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Nichts", name: "Emma :)  (PR 93)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Fakten lernen zu üben", name: "NeKr1906 (PR 92)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Eine Probe Simulation ", name: "ali123sch (PR 79)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Selbstzweifel ", name: "Charly26 (PR 39)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Zeit zur Vorbereitung", name: "Amneris123 (PR 54)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "simulationen", name: "Pseudonym (PR 35)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Smartmedix Bücher (außer Muster)",
    name: "Clea2601 (PR 76)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Entspannungsübungen", name: "Meepmoop (PR 85)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele Simulationen (unter realen Bedingungen) gemacht.-> ca. 6 Stück",
    name: "Chriso139 (PR 79)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Mir fällt tatsächlich nichts ein, ich glaube alles hat mir auf meinem Weg irgendwie geholfen:)",
    name: "20Flusensuse30 (PR 99)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr gemeinensames Präsenz lernen mit Lernpartnern (war ja aufgrund von Covid kaum möglich...)",
    name: "Einovem95 (PR 97)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "meine lernpartner, wir haben uns gegenseitig motiviert :)",
    name: "celinawerner (PR 93)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viele Übungsmaterialien (lieber doppelt bearbeiten!)",
    name: "IchBinSelbstÜberrascht (PR 93)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Die Coronazeit hat echt an den Nerven gezerrt, Freunde lange Zeit nicht zu treffen und nicht einmal die Schule zu besuchen stresst einen ohne es wirklich zu bemerken. Also wäre schön, wenn Corona nicht gewesen wär. ;)",
    name: "Miriam123 (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "ich habe mit den Büchern von Mediziner-Test gelernt, die bald öffentlich erscheinen werden",
    name: "SR27031998 (PR 96)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Bei Fakten das Geschlecht nie mitlernen xD\nDas Stark-Tms-Buch mit Strategien hab ich erst zu einem Zeitpunkt bearbeitet, als ich mir die Strategien schon selber entwickelt habe deswegen hat es mir nicht mehr so wirklich genutzt",
    name: "Bratling (PR 96)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Weniger Stress, mehr Entspannung ", name: "Ezzie712 (PR 46)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen und Bücher kostenlos über Fernleihe zu beziehen, anstatt sie für gut 200€ zu kaufen",
    name: "Annika_1807 (PR 93)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Umsonst so viel zu stressen und mich mit anderen zu vergleichen wie viel die so lernen und mich damit dann runter zu ziehen ",
    name: "GiuliaO112 (PR 88)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Zeit", name: "cica2003 (PR 58)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Einfach Simulation, hab immer entweder die vormittags Simulation oder die nachmittagssimulation gemacht, 2 mal eine komplett \n",
    name: "12345678 (PR 93)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Rund um die Uhr Strategie 2.0",
    name: "Kallahkokku?; (PR 46)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Bessere Vorbereitung in Muster", name: "Hallo123 (PR 88)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Der Kurs von mediziner-test.de war einfach gigantisch! ",
    name: "Moritz Weber (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Vorbereitungskurs von Mediziner-Test & Online Lernplattform von MedGurus",
    name: "synedrack1! (PR 92)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Unbeschwerter ohne Arbeit zu lernen ",
    name: "Blasenkathter (PR 23)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Aufbau genau durchgehen", name: "Franziska (PR 95)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Gleichzeitig für den medAT lernen ",
    name: "damsdag2 (PR 98)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Innere Ruhe hab nicht geschlafen vorm testtag",
    name: "Möööö2001 (PR 82)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Austausch und viel üben ", name: "AnnaSH05 (PR 96)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "E-Learning der Medgurus", name: "Lillifee0511 (PR 97)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Muster lernen", name: "IzayaOrihara (PR 79)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Viel Übung", name: "Emma :)  (PR 93)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Nichts😂", name: "0151-L15 (PR 96)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Atemübungen, Taktiken zur Beruhigung. Die Aufregung hat mir die Lerntests leider ziemlich versaut",
    name: ".Bobold. (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Einen Lernpartner suchen ",
    name: "Charly26 (PR 39)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Mich öfter zu zwingen eine bestimmte Anzahl an Stunden beim lernen voll zu machen, obwohl es mir nichts mehr gebracht hat.",
    name: "NeKr1906 (PR 92)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Übung in schnell verbesserbaren Tests",
    name: "Rike0606 (PR 66)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "SIMULATIONEN!!!", name: "Clea2601 (PR 76)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Vorbereitungskurs ohne davor schon angefangen zu haben mit lernen (wegen Fragen usw)",
    name: "Amneris123 (PR 54)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Günstigeres Übungsmaterial", name: "12345678 (PR 69)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Durchziehen, nicht verunsichern lassen von eigenen und anderen Ergebnissen \nGutes Selbstvertrauen haben",
    name: "20Flusensuse30 (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Der erste Vorbereitungskurs, hatte schon zu viel gelernt, war nichts neues",
    name: "Sentagioia (PR 97)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Zum Ende hin mehr Support von den Medbooster-Leuten. Zum zweiten Testwochenende ist doch sehr Ruhig geworden.",
    name: "hannover95 (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Strategien entwickeln, viel Muster üben",
    name: "IchBinSelbstÜberrascht (PR 93)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "nichts war Verschwendung ", name: "Belle176 (PR 96)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Material, das bei TV und MedNat testnah ist ",
    name: "matemate (PR 76)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Vorbereitungskurs ", name: "mg123456 (PR 69)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Einige Medgurus Bücher und unkoordiniertes Üben",
    name: "Meepmoop (PR 85)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Frühzeitiger von den Personen und Gruppen erfahren zu haben, die nachher am meisten geholfen haben aber auch das hat früh genug geklappt ",
    name: "schlottelotte (PR 90)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Durchhalten", name: "Bratling (PR 96)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Die ITB 1 und 2 Simulationen",
    name: "Albertville (PR 95)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "mehr Aufgaben auf Testniveau", name: "carolinelouisa (PR 32)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Der MedBooster Kurs und die Online Simulation ! Der Austausch auf Slack, war unglaublich hilfreich und ermutigend zum Teil auch. ",
    name: "GiuliaO112 (PR 88)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Zu viel Geld ausgegeben", name: "Emmi0907 (PR 43)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Zeit", name: "123v567! (PR 46)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "KonzTest Challenge", name: "Kallahkokku?; (PR 46)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Webinare", name: "Einovem95 (PR 97)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Ähnlicher Aufgaben wie im tms ", name: "Liselotte (PR 35)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Medbooster Vorbereitungskurs + Simulationen",
    name: "LinaSchm (PR 82)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Buch von präpkurs", name: "schmag18% (PR 93)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Support von jemandem ", name: "MedMar21 (PR 46)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "konsequent gelernt", name: "synedrack1! (PR 92)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Eine perfekte Vorbereitung haben zu wollen, Rückschläge gehören dazu.",
    name: "Miriam123 (PR 99)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Kostenlose Simulationen", name: "L12R13_% (PR 93)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen + Nachbereitung",
    name: "LarS210* (PR 95)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu lange Strategien und Nachbereitungen aufschreiben",
    name: "Selin S :) (PR 93)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "anspruchsvollere Übungsmaterialien",
    name: "leni.2612 (PR 100)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen unter realen Bedingungen ",
    name: "damsdag2 (PR 98)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Med Gurus Kurs ", name: "Ezzie712 (PR 46)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Spezifische und ausführliche Mathe Nachhilfe ",
    name: "Julia0402 (PR 76)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ganz viele Simulationen!",
    name: "Lillifee0511 (PR 97)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Das bloße Bearbeiten der Aufgaben ohne Nachbereitung",
    name: "LongDong69 (PR 62)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Lernpartner", name: "Norap1012 (PR 95)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Alles", name: "0151-L15 (PR 96)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Weniger Geld ", name: "cica2003 (PR 58)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Noch mehr MedBooster Simulationen weil sie so gut sind",
    name: "skrskrskr (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Den Kreuzblick zu erlernen! Und der Austausch mit anderen Teilnehmern.",
    name: "NeKr1906 (PR 92)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Mit medfreak&Smartmedix Textverständnis, mednat zu üben",
    name: "Schorschi7. (PR 99)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Lernpartner. Alleine fühlt man sich sehr unsicher, da die YouTube Videos einem suggerieren, dass jeder perfekt vorbereitet sein wird",
    name: "KasTac1.2 (PR 95)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Üben üben üben", name: "18240311b (PR 62)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Vorbereitungskurs ", name: "Krysoniseus (PR 99)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "mehr Freizeit", name: "anni.reitz (PR 58)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Muster", name: "Shrddboss (PR 66)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel Geld reingesteckt und nicht effizient gelernt ",
    name: "Blasenkathter (PR 23)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Besseres Ergebnis einfach nur am Ende ",
    name: "Keule12345 (PR 58)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Ständiges üben ", name: "Carlotta (PR 90)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Zu viel Material ", name: "Möööö2001 (PR 82)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Physiologiebuch lesen, Fokus mednat auf regelkreisläufe ",
    name: "varialoos  (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Vorbereitungskurs", name: "Sarahlein (PR 43)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Intensivkurs von Medbooster", name: "verkackt (PR 66)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Tipps für den Testtag an sich (Fokus nur bei sich behalten)",
    name: "dedev241 (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Jeden Tag mehrere Konz Tests",
    name: "Amneris123 (PR 54)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "ITB Bücher", name: "Blamage_4 (PR 95)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Tipps um mit der Aufregung umzugehen während der TMS schon gestartet hat (während Muster am Anfang viel es mir schwer in den Flow zu kommen)",
    name: "unicorn0108 (PR 97)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Nachbereitung\n", name: "Sentagioia (PR 97)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Die Zeit", name: "Marker-18 (PR 39)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Etwas mehr lernen", name: "juergen_huber (PR 79)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Vorbereitungskurs bei den Medboostern 😍",
    name: "Belle176 (PR 96)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "die vierte oder fünfte X-beliebige Whatsapp- oder Telegramm-Gruppe",
    name: "hannover95 (PR 96)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Das Buch zum Vorbereitungskurs mit anspruchsvolleren Aufgaben auf TMS Niveau und generell mehr verlässliches Übungsmaterial von unters. Anbietern ",
    name: "aotmkyn72 (PR 88)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Vorbereitungskurs und prüfungsnah üben",
    name: "Meepmoop (PR 85)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel im Physio-Buch lesen",
    name: "Kakashisensei (PR 88)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Testähnlichere Aufgaben", name: "marie6401 (PR 58)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Immer dran bleiben und sich nicht demotivieren lassen und natürlich immer sein Bestes geben.",
    name: "Albertville (PR 95)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Panisch zu viel Material zu kaufen:D",
    name: "schlottelotte (PR 90)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Tipps zum Zeitmamagement (Fakten lernen Reproduktionsphase)",
    name: "Emma.Medizin (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernen der neuen Strategien und der Zusammenhalt der Leute",
    name: "Emmi0907 (PR 43)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel essen zum Test mitgenommen (LOL)",
    name: "Zahnfee1602! (PR 66)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Selbstvertrauen. Ich hatte oft den großen Berg voll mit Arbeit vor Augen und dachte ich könnte keine allzu große Leistung erbringen.",
    name: "Mona9100 (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Du Werner :); und die Slack Community danke!!",
    name: "SarahBöckl (PR 85)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Quanti üben", name: "frenchyy (PR 54)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "mehr Selbstvertrauen ", name: "Cocacola (PR 73)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Präsenz Simu von MedBooster; Mathe Nachhilfe meiner Mitbewohnerin",
    name: "Einovem95 (PR 97)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Simulation von ITB", name: "carolinelouisa (PR 32)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Präsenzsimulation", name: "Ellingchen (PR 88)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "How to med, Medguru und stark Bücher ",
    name: "schmag18% (PR 93)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Vorbereitungsstudie", name: "@lalalup (PR 66)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr kostenlose Webinare <3", name: "Honigkuchen (PR 82)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Akzeptieren, dass nicht immer alles glatt laufen kann. Instagram deinstalliert, um den Druck von perfekten „Studygramern“ rauszunehmen. Werners aufbauende Worte in den kostenlosen Webinaren haben einen immer Wiederausfuhr einem Loch geholt.",
    name: "Miriam123 (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Doppelt und dreifaches Kopieren der Übungen",
    name: "mjohanna96 (PR 50)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Prüfungssimulationen zu machen.",
    name: "Alexander R. (PR 50)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "In Bücher investiert zu haben und keine Kurs gemacht zu haben + die Webinare <3 ",
    name: "butterfly195 (PR 92)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "zu viel Material gekauft ", name: "!alphcosrx_27 (PR 99)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "schwerere Konztests auf dem Markt ", name: "Eierkopf (PR 79)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Möglichst viele Simulationen ",
    name: "Nuja123. (PR 79)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Hatte keine Zeit mehr die Fakten und Figuren Bücher zu benutzen, da ich sie erst zu spät in der Abiphase bestellt habe ",
    name: "123v567! (PR 46)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Einzelnachhilfe in Mathe ",
    name: "Franziska021999 (PR 66)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Pausentage ", name: "Friederike (PR 92)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Viele Bücher ", name: "Anna2002 (PR 95)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Evtl einen Vorbereitungskurs zu besuchen",
    name: "troborobo123 (PR 76)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Intensive Nachbereitung ",
    name: "LongDong69 (PR 62)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Zu viel Zeit ", name: "Liselotte (PR 35)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Manchmal mehr Disziplin beim Üben ", name: "Darlingg (PR 88)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Kontinuierliche Vorbereitung über einen längeren Zeitraum",
    name: "lediov369 (PR 100)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Zu viele Bücher", name: "MedMar21 (PR 46)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Volleybälle bei Figuren lernen und schwierigere Fakten",
    name: "Marie-3001 (PR 98)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Lernpartner ", name: "cica2003 (PR 58)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "E learning der Medgurus war unnötig ",
    name: "K8f3hq17! (PR 93)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Volleyball-Figuren, mehr Übungshefte für Quanti und D+T",
    name: "Laura-3001 (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Konstant gelernt und Pause eingehalten ",
    name: "Hallo123 (PR 88)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "E-Learning von Medgurus", name: "leni.2612 (PR 100)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Webinare zu Quanti", name: "Nicii_03 (PR 76)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernplan, verschiedene Strategien, Stärken schulen",
    name: "Annie10.8 (PR 79)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "nichts man lernt ja auch aus Fehlern.",
    name: "hugendubel (PR 96)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Simulation ", name: "Nicewieich? (PR 92)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Tägl. Lernen, Orginalsimulation, Langes Lernen am Stück ",
    name: "Krysoniseus (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "So viele Übungsbücher, Simulationen sind viel besser",
    name: "Emily Lüder (PR 54)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "entspannter zu sein,in realen Bedingugen zu lernen uf",
    name: "Schademarmelade (PR 29)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Medbooster kennenlernen ",
    name: "Blasenkathter (PR 23)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viele Simualtionen, da ich dadurch einfach nur fertig war und übungsmaterialien verschwendet habe weil man gerade im zweiten Teil extrem unkonzentriert ist also ich :)",
    name: "Julia0402 (PR 76)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Geld, ergo Vorbereitungskurse, ", name: "nahidddd (PR 32)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Üben ", name: "Möööö2001 (PR 82)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Themen lernen für MedNat und Textverständnis",
    name: "Kräutertee (PR 100)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Selbstdisziplin 😅 und mehr (vielfältigeres, schwierigeres) Übungsmaterial",
    name: "C20L11_M (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Besonders Konztest üben",
    name: "Idefix0112 (PR 66)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Erst nach Tipps erkundigt und dann erst angefangen Aufgaben zu machen. Erstmal sollte man ein paar Aufgaben selbst eine Woche machen und kann danach nach verschiedenen Strategien suchen, aber erstmal sollte man Anfangen!!!! Über 8h Tag 7 Tage die Woche war zu viel, sodass ich zwei Wochen gar keine Motivation mehr hatte",
    name: "KasTac1.2 (PR 95)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Ruhe in die eigene Vorbereitung einbringen ",
    name: "Elli.1897 (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Simulationen ", name: "Victoria902 (PR 93)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Smartmedix Figuren und Fakten, Smartmedix Schlauchfiguren ",
    name: "sophie126 (PR 73)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Schwerere Aufgaben ", name: "Charlotte 1* (PR 62)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "NACHBEREITUNG!!!!", name: "Blamage_4 (PR 95)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Vor dem Kurs schon viel eigenständig (und teilweise falsch) zu lernen",
    name: "Lalelu2705 (PR 95)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "alles lockerer anzugehen ", name: "GodBless (PR 54)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "In den letzten Monaten vor dem TMS jede Woche eine Testsimulation unter echten Bedingungen durchzuführen",
    name: "MarieWi  (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel Zeit mit Konzentration/Sorgfältiges Arbeiten verbracht bzw. zu oft die gleichen Tests bearbeitet, da im TMS komplett neue Kombinationen drankamen.",
    name: "cherrie_crown (PR 98)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "günstigere Angebote - der TMS ist einfach echt teuer",
    name: "17Carat! (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Stark Simulationen ", name: "IzayaOrihara (PR 79)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Medizin-Bücher ", name: "anni.reitz (PR 58)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Vielleicht hätte ich doch ein Quanti-Seminar belegen sollen.",
    name: "r1.e2.y3. (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen und Training mit MedGurus ",
    name: "IsaHelen (PR 93)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Alles ", name: "Keule12345 (PR 58)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "-", name: "Prallino (PR 99)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Entspannungsübungen", name: "Rike0606 (PR 66)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Medgurus Kopendium neu Kaufen ",
    name: "varialoos  (PR 73)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Früher mit einigen UT anfangen", name: "Bill1006 (PR 85)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "ITB kurz vorher nochmal intensiv durchgegangen",
    name: "Kathi123 (PR 82)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel Übungsmaterial, auch habe ich immer gleich Kompendien geholt statt einzelne Bücher und 2 davon kaum angerührt. Allgemein habe ich kaum was durchgearbeitet und vielleicht nur 1/4–1/5 von dem benutzt was ich gekauft habe. ",
    name: "WinnieBooh (PR 100)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Nix war super so :) ", name: "Schokoeis (PR 95)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Vorbereitungskurs bei MedBooster",
    name: "maxi1708 (PR 66)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "MedGurus Quanti", name: "henningkeps (PR 99)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mit mehr Übersicht die Bücher durcharbeiten, mehr Ergebnisse aufschreiben ",
    name: "Satisfyer (PR 93)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Die TMS-Vorbereitung als Marathon angesehen und immer das Gleichgewicht zwischen Anspannung und Entspannung im Optimum gehalten",
    name: "hannover95 (PR 96)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Viel zu viel für Quanti geübt", name: "dedev241 (PR 99)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Faktensets mit doppelten Fakten", name: "Textmarker (PR 96)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Werners Webinare, Stark Simulationen",
    name: "Kakashisensei (PR 88)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Viele simulationsbücher zu kaufen",
    name: "VK2107SR (PR 79)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Vorher anzufangen und Motivation oder Disziplin beibehalten",
    name: "okletsgo123 (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernplan geschrieben, hat mein Gewissen beruhigt",
    name: "medentstudent (PR 96)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "MedGurus Bücher", name: "Hanxxan  (PR 43)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Günstigere Materialien", name: "Ha2203nna (PR 46)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Austausch mit anderen",
    name: "VenitEnimPotest (PR 32)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Meditrain ausgenommen Diagramme/Tabellen",
    name: "aotmkyn72 (PR 88)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "mindset von 3 wochen davor schon früher haben",
    name: "s7lasnnn (PR 69)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "MedGurus Bücher, Quantikurs MB",
    name: "JMPB2002 (PR 99)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Vorbereitungskurs", name: "marie6401 (PR 58)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mein Wissen/Erfahrung von heute. Ersteinmal in die Thematik einzutauchen und zu 100% zu verstehen (was der TMS ist und und du ein gutes Ergebnis bekommst, ist unglaublich zeitintensiv",
    name: "Gewitterchen (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele verschiedene Anbieter kombiniert",
    name: "matemate (PR 76)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Sich online bei den Medgurus zu vergleichen, hat einen nur verrückt gemacht ",
    name: "Emma.Medizin (PR 79)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Früher die Meedbooster Community entdecken ",
    name: "Leonado🌞 (PR 82)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen, Physiologiebuch lesen",
    name: "Lxyrx_17 (PR 82)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Plakate für jeden Untertest", name: "Ellipelli (PR 82)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Ich bin so glücklich mit meinem Ergebnis, dass ich nichts an meiner Vorbereitung ändern würde ",
    name: "Christin.hlk (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Neben Kursen und Simulation auf jeden Fall der Austausch mit verschiedenen Lerngruppen und nicht nur einem lernpartner um unterschiedliche Ansätze zu lernen ☺️",
    name: "schlottelotte (PR 90)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Bücher ohne Übungen zeitgleich zu bearbeiten",
    name: "Schnuffel99 (PR 62)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Ich hätte mich mehr um Figuren und Fakten kümmern müssen ",
    name: "Vale0912 (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Viele Simulationen ", name: "Zahnfee1602! (PR 66)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Nichts. Jedes Übungsmaterial lohnt sich auf die ein oder andere Weise. ",
    name: "Mona9100 (PR 99)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Frühere Erkenntnis, dass man eher ein besseres Ergebnis erzielen kann je mehr man trainiert/nachbereitet",
    name: "M.tnzr21 (PR 62)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Das Beste, was mich auf den TMS vorbereitet hat, war der Kurs bei Medbooster mit einer anschließenden Simulation. Kann diese wirklich weiterempfehlen. ",
    name: "BliBlaBlub (PR 88)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Üben obwohl ich gemerkt habe, dass ich nicht mehr kann.",
    name: "Cocacola (PR 73)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Zeit, mehr Geld für Kurse",
    name: "Pippi Langstrumpf (PR 35)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Konzi schon früh angefangen zu üben",
    name: "frenchyy (PR 54)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viele Übungsmaterialien in nicht optimaler, Test Niveau  naher Qualität.",
    name: "IncurableOptimist (PR 43)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Ein jahr davor anzufangen 😂", name: "MXX12345 (PR 58)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Kurs bei MedBooster :)", name: "1450BGS7 (PR 82)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Smartmedix ", name: "cule—124 (PR 88)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Persönlich hätte ich selbst nach der Simulation im Kurs selbst früher mit eigenen Simulationen weitermachen sollen.",
    name: "PeristaltusPork (PR 76)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Eine vorherige gesamte Simulation",
    name: "@lalalup (PR 66)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Kurs", name: "Ellingchen (PR 88)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr Erfahrungsberichte", name: "Wasserflasche (PR 79)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Ackern Ackern Ackern", name: "mjohanna96 (PR 50)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Lernplattform von Medgurus. Zu viel Stress, Quanti Aufgaben von Medgurus (zu unrealistisch, eher Medbooster!)",
    name: "Honigkuchen (PR 82)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "gemeinsame Simulation mit anderen", name: "schnell10 (PR 79)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Vorbereitungskurs, Nachbereitung ",
    name: "!alphcosrx_27 (PR 99)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Mehr Material zu kaufen ", name: "#ylime2021 (PR 92)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "vertiefende Lernvideos zu Strategien und Basics zu allen Untertests, vor allem für Quanti z.B. für Konzentrationsaufgabe, in dem Video muss Strategie, Beispiel und Fallstricke bearbeitet werden, am besten auf mehreren Wegen",
    name: "MarcellD’Avis (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Schlauchfiguren und Mathe-LK",
    name: "123v567! (PR 46)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu früh anzufangen und Übungsmaterial mehrfach zu verwenden.",
    name: "Alexander R. (PR 50)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Mehr mögliche Simulationen ", name: "Pseudonym  (PR 100)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Simulation ", name: "Anna2002 (PR 95)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Konzi zu trainieren ", name: "Eierkopf (PR 79)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Eine Simulation in Präsenz ", name: "Zahni123 (PR 90)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen ohne Ende bearbeitet ",
    name: "Traumaerztin2021 (PR 79)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Der Vorbereitungskurs von medgurus!!!",
    name: "LeonieBe912 (PR 82)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Selbstvertrauen, innere Ruhe",
    name: "ErsterAugust (PR 82)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Routine ", name: "Liselotte (PR 35)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "So viele Bücher zu kaufen ",
    name: "Franziska021999 (PR 66)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "evt. verschiedeneres Material, um unterschiedliche Aufgabenstellungen kennenzulernen ",
    name: "Februar+22 (PR 95)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Entspannt bleiben", name: "ShMJ0504 (PR 92)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Nicht so effizientes Üben", name: "phini123 (PR 99)" },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "nichts ", name: "x3_ellibeth_x3 (PR 96)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "MedGurus Bücher-Komplettpacket + Simulationen von Stark",
    name: "Jolanda! (PR 96)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Smartmedix Bücher (medbooster hatte genug material)",
    name: "Laki6saki7 (PR 99)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "jemand, der mir gesagt hätte, dass es besser wäre, früher anzufangen",
    name: "xyz978%! (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Kontinuierliches Üben, also jeden Tag und in der Reihenfolge des original TMS ",
    name: "K8f3hq17! (PR 93)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Erimed Muster (Panikmache)", name: "Jonas%AC (PR 99)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Ein Training mit Maske, mich hat diese beim Test ziemlich abgelenkt",
    name: "Schlodde56 (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen, richtige Reihenfolge der Untertests",
    name: "Leoblucy (PR 20)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "MedGuru Quanti Buch und MedFreak Bücher ",
    name: "Darlingg (PR 88)",
  },
  { frage: "Was hättest du dir noch gewünscht?", tipp: "Alles top", name: "Joker8989 (PR 95)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Kontinuierliches Üben, Simulationen",
    name: "Anonymous02 (PR 93)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "ITB Consulting ", name: "Marie-3001 (PR 98)" },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "Mehr Simulationen auf Papier, auch in den Kursen. Zusätzlich zum Konz-Block mehr ausgedrucktes Übungsmaterial",
    name: "lini1503 (PR 54)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "langzeitige Vorbereitung",
    name: "Graut1g3r (PR 100)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "ITB Consulting, hatte aber auch nicht Version III",
    name: "Laura-3001 (PR 99)",
  },
  {
    frage: "Was hättest du dir noch gewünscht?",
    tipp: "ich glaube, ich habe mich für meine Verhältnisse bestmöglich darauf vorbereitet.",
    name: "ypB6d8Fj (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Kreuzblick lernen. nicht überarbeiten. andere nach tipps fragen.",
    name: "hugendubel (PR 96)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Das Einleitungsbuch beim Medgurus Kompendium, da alles nochmal in den einzelnen Büchern steht",
    name: "Nicii_03 (PR 76)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele übungsmaterialien zu haben und die kurzen Test schnell anzufangen auf Zeit zu üben aber die größeren eher Intesiv also nicht auf Zeitdruck sondern die Aufgaben verstehen.",
    name: "Julia0402 (PR 76)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Nichts. Ich glaube alles hat im Endeffekt dazu beigetragen, dass ich dieses Ergebnis erzielt habe. ",
    name: "Lockencharlie  (PR 93)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Vorbereitungskurs bei Medbooster",
    name: "maxi1708 (PR 66)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Intensive Vorbereitung von Quanti und Textverständnis ",
    name: "C.L.2609 (PR 43)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Nachbereitung ", name: "Kräutertee (PR 100)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "MedFreak - Bücher", name: "Puddlon2002 (PR 92)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Früh mit den Aufgaben angefangen",
    name: "Alexander (PR 95)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "zu viel stressen :)", name: "Brooklyn99 (PR 100)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Fokus aufs Abi legen und den Druck für den TMS rausnehmen",
    name: "Rhabarber (PR 85)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Telegram Gruppe", name: "Nicewieich? (PR 92)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen jedes Wochenende 4 Wochen vor dem TMS (die besten waren von MedBooster)",
    name: "skrskrskr (PR 85)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Medgurus Mathekurs", name: "Clara2001 (PR 73)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Das Internet nach verschiedenen Strategien durchsucht und nicht aufgeben, bei Aufgaben die man nicht versteht ",
    name: "KasTac1.2 (PR 95)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Verrückt machen, dass ich den Faller nicht ganz geschafft habe durchzulesen ",
    name: "LauraBue (PR 92)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Pausen und Zeitstoppen", name: "Marietta (PR 92)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Unnötige Materialien gekauft",
    name: "Schademarmelade (PR 29)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mit den Büchern zu lernen und das regelmäßig zu lernen",
    name: "Finnja24 (PR 90)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Sich von schlechten Ergebnissen demotivieren zu lassen und manchmal den Glauben an sich zu verlieren ",
    name: "Jazjaz__ (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Den Kurs bei MedBooster und mich mit anderen auszutauschen",
    name: "Lalelu2705 (PR 95)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel Material im Vorfeld gekauft",
    name: "LH1999LH (PR 76)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "3 Simulationen in Echtzeit eine Woche vor dem TMS",
    name: "cherrie_crown (PR 98)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viele Bücher gekauft, bin nicht durchgekommen ",
    name: "Sph999999 (PR 93)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Übungsaufgaben", name: "anni.reitz (PR 58)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Nicht strukturiertes Vorgehen (Planung)",
    name: "Elli.1897 (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Nichts", name: "Keule12345 (PR 58)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Ich habe mich viel zu sehr gestresst und hätte entspannter rangehen können.",
    name: "Erdbeertorte (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Übung und Nachbereitung ",
    name: "varialoos  (PR 73)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel Zeit investiert, zu wenig entspannt",
    name: "GodBless (PR 54)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Klingt blöd, aber nicht zu viel zu tun?! Ich habe mich eher Übungen intensiv gewidmet und auch viele pausentage (teilweise auch Wochen) gehabt. ",
    name: "WinnieBooh (PR 100)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel an einzelnen Ergebnissen den Erfolg gemessen und daran emotional aufgehalten. Am Testtag kann eh nochmal alles ganz anders sein :)",
    name: "r1.e2.y3. (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Private Simulation in Büchern",
    name: "twin1.sto (PR 82)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Strategien zusammenfassen", name: "Gartenzwerg (PR 98)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen, viele Simulationen. Webinare",
    name: "henningkeps (PR 99)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "-", name: "Prallino (PR 99)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Lernplan", name: "Serkan19 (PR 4)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Med gurus ", name: "himbeertörtchen  (PR 66)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viel versucht zu reflektieren, im Kopf zu haben, dass man immer besser werden kann ",
    name: "dedev241 (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel üben und verrückt machen",
    name: "Loisimoisi (PR 69)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Alles genau durchplanen zB wann auf Toilette, wann etwas essen; sehr viele Simulationen gemacht zu haben für Ausdauer ",
    name: "unicorn0108 (PR 97)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Auf keinen Fall irgendetwas auswendig lernen versuchen für textverständnis/mednat",
    name: "Schokoeis (PR 95)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Consistency is key", name: "2mina4u  (PR 93)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "webinar vor dem Testtag ...sry, aber war echt überflüssig und ging gar nicht",
    name: "lauramarie.28 (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mehrtägige Pausen zwischen lerntagen und kein Druck machen",
    name: "VK2107SR (PR 79)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Mathe Intensivkurs medbooster", name: "Trex1234 (PR 66)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen und Lernpartner",
    name: "Hanxxan  (PR 43)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Die ganzen Übungsbücher (zu viele) ",
    name: "Tentakel  (PR 62)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Medgurus Bücher", name: "Philipp19 (PR 96)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Das Mathe-Bootcamp der Medgurus 🙃",
    name: "srhdb_20 (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "frühzeitig anfangen zu lernen",
    name: "Graut1g3r (PR 100)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Smartmedix, Vorbereitungskurse ",
    name: "Satisfyer (PR 93)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Vorbereitungskurs LiveCalls und Medgurus Bücher/Smartmedix Quanti",
    name: "aotmkyn72 (PR 88)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "zu alte vorbereitungsbücher, eine zu gründliche nachbereitung zum ende hin wahrscheinlich ",
    name: "Anna56789 (PR 97)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Trainieren, trainieren, trainieren ",
    name: "Marieke12 (PR 69)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Für Konzentriertes und Sorgfältiges Arbeiten zu Üben ",
    name: "Nina2021 (PR 92)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Komplettsimulationen", name: "Ellipelli (PR 82)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Parallel zu arbeiten ", name: "Annamich (PR 17)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ganz viel üben und nicht an Büchern sparen.",
    name: "maxiquaki13! (PR 88)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "üben vor kurs", name: "s7lasnnn (PR 69)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Übungen nachbereitet, meditation",
    name: "Schnuffel99 (PR 62)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Staf vorbereitungsstudie", name: "Joella L. (PR 90)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ganz klar die Simulationen! Das gibt einem schon einen sehr guten Einblick in den eigentlichen Testtag (bspw. wie anstrengend der Tag ist)",
    name: "Mona9100 (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Einige Smartmedix Simulationen ",
    name: "Gewitterchen (PR 85)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Pausen", name: "Cocacola (PR 73)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu viel wert auf schwer trainierbare UT zu legen ",
    name: "jasmeme1 (PR 58)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele Simulationen unter Prüfungsbedingungen (Zeitdruck, Nebengeräusche, Maske...)",
    name: "BellaB2! (PR 99)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Üben ohne nachzuarbeiten ", name: "Leonado🌞 (PR 82)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Einer kleinen Lerngruppe beigetreten, das Erlernen der  Entspannungstechniken ",
    name: "IncurableOptimist (PR 43)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Das Medgurus Figuren und Fakten Buch, außerdem habe ich 3 Bücher nicht benutzt, weil ich nicht so viel Material durcharbeiten konnte. ",
    name: "Christin.hlk (PR 85)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Viele Simulationen", name: "XYugl42! (PR 32)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Mich zu sehr von meinen schlechten UT‘s beeinflussen lassen ",
    name: "Vale0912 (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele Simulation (5-6)",
    name: "ZukunftsZahni12  (PR 93)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Zu wenig Figuren lernen, zu sehr auf untertests verlassen, die mir in den Probedurchgängen sehr gut gelegen haben (Textverständnis, Diagramme)",
    name: "Antoniaa (PR 43)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Medgurus", name: "cule—124 (PR 88)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Zeitaufwand ", name: "Pippi Langstrumpf (PR 35)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mich mit anderen ausgetauscht! Slack Community einfach beste <3",
    name: "Honigkuchen (PR 82)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Einzelne UTs vollständig bearbeiten, lieber vllt die Hälfte dafür sorgfältig mit Analyse bei der Nachbearbeitung ",
    name: "Wasserflasche (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Das Simulations Wochenende vor dem eigentlichen TMS",
    name: "Marleen07 (PR 90)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Online Lernplattform", name: "schnell10 (PR 79)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Zeitig genug angefangen",
    name: "#ylime2021 (PR 92)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "MedGurus Kurs, je nach Perspektive generell Kurse, sowohl online als auch offline",
    name: "MarcellD’Avis (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Regelmäßiges Üben, vor allem Quanti und Diagramme.\nVor allem ganze Testsimulationen, mit Uhr, mit prüfungsnaher Zeiteinteilung und allem was dazu gehört sehr ernst nehmen.",
    name: "Alexander R. (PR 50)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Kreuzblick lernen (funktioniert letztendlich nicht so gut wie erwartet)",
    name: "claaaara (PR 82)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Überhaupt durchzuhalten ", name: "Eierkopf (PR 79)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "MedGurus", name: "SoMaDe1202 (PR 66)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Die how to med Konz-Unterlagen, kostenlose Webinare",
    name: "LeonieBe912 (PR 82)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Der Kurs war gut, aber hatte viele schon bekannte Infos (das hat teilweise Stunden in Anspruch genommen - da hätte ich lieber gezielter in der Gruppe geübt oder ausgetauscht)",
    name: "ErsterAugust (PR 82)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Reflektion ", name: "Franziska021999 (PR 66)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "ITB I und II; zu viele Aufgaben mit ungenügender Nachbereitung ",
    name: "Februar+22 (PR 95)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Kreuzblick lernen", name: "Luisa240 (PR 99)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "TMS-Apps und alle Bücher die ich mir gekauft haben außer Medgurus, Smartmedix und Stark",
    name: "x3_ellibeth_x3 (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele verschiedene Anbieter",
    name: "phini123 (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Früh anfangen die schlecht trainierbaren UT zu üben (November 2020), Keinen Kurs von MedBooster zu buchen",
    name: "Meerglitzern (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Einen Lernpartner zu suchen",
    name: "Laki6saki7 (PR 99)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "das Kopieren aus Büchern um Geld zu sparen, einfach reinkritzeln spart etwas viel Wichtigeres: Zeit",
    name: "xyz978%! (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Lernpartnerschaft", name: "Jonas%AC (PR 99)" },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Stress, Vergleichen mit Menschen die andere Stärken haben als man selbst ",
    name: "Eiskaffee (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Anmeldung bei Medbooster und Nutzung von SLACK ",
    name: "Darlingg (PR 88)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Kurs bei medgurus", name: "Helikopter3008 (PR 50)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ein Probetest bei den Medgurus",
    name: "Marie-3001 (PR 98)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Jeden Tag ein Fakten und Figuren lernen zu machen, ohne es zu reflektieren",
    name: "Schlodde56 (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ein Probetest von Medgurus ",
    name: "Laura-3001 (PR 99)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Erimed Bücher", name: "Joker8989 (PR 95)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Nachbereiten, nachbereiten, nachbereiten!!😁 ",
    name: "Panda2002 (PR 97)",
  },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "Ja, teilweise.", name: "lini1503 (PR 54)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Kurs bei MedBooster ", name: "Nicii_03 (PR 76)" },
  { frage: "Wovon rätst du anderen Teilnehmern ab?", tipp: "MedGurus Kurs ", name: "Le0nie.f (PR 79)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulation und die Stark Verlag Bücher. Sowie die mentale Vorbereitung! ",
    name: "Lockencharlie  (PR 93)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "Grundkenntnisse Mathe aufbauen zu wollen ",
    name: "Paula17199 (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Früh angefangen, jeden Tag dann aber nur ein bisschen",
    name: "C.L.2609 (PR 43)",
  },
  {
    frage: "Wovon rätst du anderen Teilnehmern ab?",
    tipp: "irgendwie hat alles, was ich gemacht habe, einen Teil beigetragen",
    name: "ypB6d8Fj (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: 'Probetest unter "Realbedingungen" (von den MedGurus)',
    name: "Puddlon2002 (PR 92)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Kontinuierlich jeden Tag ein bisschen zu machen, denn bei zu viel verliere ich die Motivation. Habe auch immer die Untertest geübt, auf die ich gerade Lust habe. Habe mich dann auf meine Stärken konzentriert (meine Schwächen waren sowieso bei den schwer trainierbaren Untertests).",
    name: "Gurke0815 (PR 92)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernplan, Lerntagebuch, Reflektieren, MedBooster Kurs, mit Kursleiter/Freunden/Menschen austauschen",
    name: "Brooklyn99 (PR 100)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Eigene Simulationen", name: "asw.2472 (PR 73)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Entspannt reingehen", name: "Nicewieich? (PR 92)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Früh angefangen und dran geblieben",
    name: "Alina0101 (PR 99)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Medbooster Seminar", name: "Clara2001 (PR 73)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Die Webinare und der Austausch über die Slack-Gruppe. Sowohl vom Inhalt als auch für die Psyche, Motivation etc...",
    name: "LauraBue (PR 92)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen, regelmäßiges Üben, umfangreiches Material",
    name: "Jazjaz__ (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Fast nur Muster zuordnen und die Tests, die man gut trainieren kann, geübt",
    name: "RegV1234 (PR 82)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Pausen einlegen!", name: "Layla181 (PR 90)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Komplett Simulation ", name: "LH1999LH (PR 76)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Übungen!", name: "C20L11_M (PR 79)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Der Kurs bei den Medboostern!",
    name: "Elli.1897 (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Es während dem Abitur zu schreiben und sich nicht abschrecken zu lassen von Berichten und Warnungen von Influencer bzw. ehemaligen Teilnehmern",
    name: "xxxlucexxx (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Die MedGurus Bücher 📚 haben mir glaube am meisten gebracht.",
    name: "Erdbeertorte (PR 99)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Lerngruppe", name: "Eslemayse (PR 93)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Mehrere Simulationen", name: "MOSY#07! (PR 62)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Nicht Aufgeben", name: "Smiley8765 (PR 93)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen, Medbooster Kurs, Slack",
    name: "Luise2001 (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viele Simulationen - mit medbygrangers video!",
    name: "emmi1107* (PR 97)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Telegram Gruppe", name: "GodBless (PR 54)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "eine Simulation - die Erschöpfung zum Ende hin unterschätzt man sonst",
    name: "17Carat! (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Lernpartner zu finden.", name: "r1.e2.y3. (PR 85)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Die Konz Tabelle", name: "Ginny27& (PR 88)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "jeden Tag einen KonzTest",
    name: "Gartenzwerg (PR 98)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Früh anfangen", name: "Prallino (PR 99)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernpartnerin!!!!",
    name: "himbeertörtchen  (PR 66)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Regelmäßiges üben damit man sich bei den Übungen sicher fühlt",
    name: "12354678 (PR 92)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Kurs (v.a. Quanti) und Bücher",
    name: "Bill1006 (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mich jeden Tag hingesetzt, egal wie lange/kurz, klaren Kopf bewahrt",
    name: "Schokoeis (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Alles mit meinen Lernpartnern durchgezogen!!!",
    name: "Malaikofta1234 (PR 69)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Eine lange sorgfältige Vorberitung um Routine rein zu bekommen",
    name: "Jonathan (PR 99)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mich bei MedBooster angemeldet zu haben ",
    name: "Tallibeii  (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "medbooster kurs, medby granger simulation",
    name: "lauramarie.28 (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Webinare kostenlos von medbooster",
    name: "Leamuster (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "So viele und verschiedene Tests zum konzentrierten und sorgfältigem Arbeiten gemacht",
    name: "Jeanzzzz (PR 54)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Tägliches Training", name: "Tentakel  (PR 62)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Viel Üben, vor Allem Simulationen",
    name: "Toeftel_1 (PR 92)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Einen Kurs zu buchen und mind. eine simulation zu machen",
    name: "w0ll€_141021 (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Austausch mit Lernpartner",
    name: "CaptainJack (PR 88)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Test-Simulationen", name: "srhdb_20 (PR 85)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Nicht zu viel gelernt",
    name: "Kathi_090521 (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulation und nacharbeiten ",
    name: "Teetasse (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "in regelmäßigen Abständen Simulationen ",
    name: "Lissi 123 (PR 92)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Die Bücher und die Online-Übungen von Medgurus so viel wie möglich bearbeiten und nachbereiten.",
    name: "Pilzparty (PR 93)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Keine Ahnung", name: "AutoBus138 (PR 66)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Strategien zu recherchien (Youtube, Bücher, Webinar, Kurse, etc) und an Webinare teilnehmen (An dieser Stelle danke Werner :)",
    name: "okletsgo123 (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Wiederholen wiederholen, ganz viel Routine reinbringen din die kurzen untertests",
    name: "Lisadjdj (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernplan von anfang an, Bücher und Kurse",
    name: "Feile249 (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen, und Regelmäßiges Üben",
    name: "Mas3113uuu (PR 92)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen! Lernplan erstellen",
    name: "Anna56789 (PR 97)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Ganz viel Üben!", name: "Nina2021 (PR 92)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Stärken ausbauen und Schwächen trainieren",
    name: "möwenpick (PR 79)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Med Booster Kurse", name: "Annamich (PR 17)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Übungen auf Zeit ", name: "Srn7373! (PR 35)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Medbooster Kurs", name: "s7lasnnn (PR 69)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ein fester Lernplan und viele Simulationen ",
    name: "Joella L. (PR 90)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Entspannen", name: "caroline  (PR 85)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Immer weiter gemacht zu haben",
    name: "Gewitterchen (PR 85)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "viel üben", name: "Jankrtr4 (PR 97)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen!!! Und mit lernpartnern ausgetauscht ",
    name: "jasmeme1 (PR 58)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Möglichst viel Übungsmaterial durcharbeiten",
    name: "Leo363200 (PR 88)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Einen Vorbereitungskurs mit den Meedboostern (tolle Tipps, neue Verfahren/Methoden, weniger Angst durch Austausch mit anderen) und eine Simulation zuhause (gewusst wie man mit Blackouts/dem Zeitdruck/der Erschöpfung umgeht) ",
    name: "Leonado🌞 (PR 82)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Die Simulation im Vorbereitungskurs mit Medbooster und der Austausch über Slack bzgl. Strategien. Auch wenn man sich gegenseitig geholfen hat konnte man sowohl als Helfende:r, als auch als Suchende:r seinen Horizont erweitern. ",
    name: "Christin.hlk (PR 85)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mich auf meine guten UT‘s fokussieren",
    name: "Vale0912 (PR 73)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Konsequent Muster üben", name: "Antoniaa (PR 43)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ausführliche Nachbereitung, Simulationen",
    name: "M.tnzr21 (PR 62)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Verschiedene Anbieter zu benutzen, Austausch zu suchen",
    name: "Ami2401! (PR 98)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernplan und Lernerfolg schwarz auf weiß",
    name: "Wasserflasche (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "komplette Simulationen in Papierform",
    name: "schnell10 (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Real- und Onlinesimulationen und Austausch mit anderen Teilnehmern (online)",
    name: "MarcellD’Avis (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulationen und Austausch über Slack",
    name: "claaaara (PR 82)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mit Lernpartner zu lernen ",
    name: "SoMaDe1202 (PR 66)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Ein strukturierter Lernplan ",
    name: "Zahni123 (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Simulation/Lernmaterial aus Büchern(nachbereitet natürlich)",
    name: "ErsterAugust (PR 82)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Mit Lernpartnerin lernen", name: "Hzaw1921 (PR 23)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Bücher kaufen -->  Fahrplan erhalten; MedBooster Simulation --> Kontakt/ nicht allein da stehn",
    name: "Februar+22 (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Lernplan erstellt und den MedboosterKurs",
    name: "x3_ellibeth_x3 (PR 96)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "MedBooster OnlineVeranstaltungen und Simulationen + Starkbuch",
    name: "MoFi9513 (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Früh anfangen die gut trainierbaren UT zu üben (November 2020)",
    name: "Meerglitzern (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "nicht aufzugeben... obwohl ich in den Simulationen nicht sehr gut war, am TMS teilzunehmen",
    name: "xyz978%! (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: " Viele Simulationen ",
    name: "MedBooster28.06 (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Stetig dranzubleiben; mir die kostenlosen Webinare von MedBooster anzuschauen (das hat mich immer seehehr beruhigt und ich fand die Informationen wirklich wertvoll)",
    name: "Lenis.Med.Journey27 (PR 82)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Vorbereitungskurs, Simulationen und deren Nachbesprechungen",
    name: "violet03 (PR 95)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Euren Kurs mitgemacht!\n", name: "Fini2020 (PR 73)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "viele verschiedene Simulationen, mit Lernpartnern regelmäßig ausgetauscht, regelmäßiges Nachbereiten der Aufgaben und Fehler Analyse ",
    name: "Eiskaffee (PR 73)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Quantikurs bei nedbooster",
    name: "Helikopter3008 (PR 50)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Das Lernen mit einem Lernpartner und der Kurs",
    name: "Schlodde56 (PR 96)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Simulation mit Maske", name: "LadyBariecue (PR 35)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Früh genug angefangen, Testsimulation von Medbooster und ITB Simulationen",
    name: "Joker8989 (PR 95)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Kontinuierlich gelernt und auf die Tipps gehört die mir von guten Teilnehmern der letzten Jahre gegeben wurden. Einen klaren Lernplan den ich nach der ersten Simulation (8 Wochen vorm Test) angepasst habe.",
    name: "1MtbArzt (PR 98)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Auszeit nehmen und bewusst machen, dass ich genug gemacht habe und gut bin",
    name: "katta_jd (PR 90)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Zu viel für Online Plattformen gezahlt. Habe ich nicht oft verwenden können.",
    name: "lini1503 (PR 54)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Feste Tagesabläufe, Austausch mit anderen, viele testnahe Simulationen, ",
    name: "Trofflromselol (PR 99)",
  },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Leichte UT‘s gelernt ", name: "Le0nie.f (PR 79)" },
  { frage: "Was ist dein Top-Tipp für andere Teilnehmer?", tipp: "Üben üben üben ", name: "Paula17199 (PR 99)" },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "Mit Zeitdruck (Timer) zu üben",
    name: "Sonnenblume (PR 79)",
  },
  {
    frage: "Was ist dein Top-Tipp für andere Teilnehmer?",
    tipp: "regelmäßiges Trainieren der Bearbeitungsstrategien",
    name: "ypB6d8Fj (PR 90)",
  },
];
module.exports = { tipps };
